default: &default
  adapter: postgresql
  encoding: unicode
  port:     5432
  username: postgres
  password: postgres

development:
  <<: *default
  host:     localhost
  port:     5432
  username: postgres
  password: postgres
  database: 'goway_development'

production:
  <<: *default
  host:     82.180.132.184
  port:     5432
  username: exoticgrouptravel
  password: WellAuthenticated@34
  database: 'exoticgrouptravel'

